on:
  push:
jobs:
  build:
    runs-on: macos-latest
    env:
      LDFLAGS: -L/usr/local/opt/openblas/lib
      CPPFLAGS: -I/usr/local/opt/openblas/include
    steps:
    - uses: actions/checkout@v2
    - run: brew upgrade
    - run: brew install openblas
    - run: |
        cd $HOME/work/openturns
           git clone https://github.com/jeromerobert/hmat-oss.git hmat-oss
           cd hmat-oss/ 
           cmake -DBUILD_EXAMPLES=OFF -DCBLAS_INCLUDE_DIR=/usr/local/opt/openblas/include -DCMAKE_MACOSX_RPATH=ON .
           make install -j$(sysctl -n hw.logicalcpu)
    - run:  |
        cmake -DUSE_R=OFF \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror" \
        -DUSE_SWIG=OFF \
        -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 .
    - run: make install -j$(sysctl -n hw.logicalcpu)
    - run: ctest -R hmat -j$(sysctl -n hw.logicalcpu) --output-on-failure --timeout 100
